### ISSUE TITLE
argotlunar AU makes FCPX fail to restore window layout on launch

### ISSUE THREAD

**Issue by arvidtp** [mourednik/argotlunar#1]
Hi,

Argotlunar is quite cool - nice to have an open source granular AU/VST.

However, when the AU is installed, it causes Final Cut Pro X 10.1.4 to fail to restore its window layout and therefore freeze on launch. OS X 10.9.5. As soon as I removed the plugin, FCPX is fine. This is a problem i've seen before with another AU – [sickndestroy](http://www.ineardisplay.com/freebies/). I contacted the developer and they fixed the issue. Seems that argotlunar has the same issue.

Have not tested in FCPX 10.2 on OS X 10.10 yet.

 Yes – i'd say the fault is mostly apple's for having such a touch AU implementation in FCPX, but thought you'd like to know. Thanks!

**Comment by mourednik** [comment]
I suspect that the problem will be resolved if I update the plugin to use the latest version of the JUCE framework. I'll try that out soon.
