### ISSUE TITLE
Crashes on opening plugin 

### ISSUE THREAD

**Issue by 8yth8yrd** [mourednik/argotlunar#10]
Im running the last version of MacOS and Flstudio. After getting around the jank that is verifying a plugin on this operating system and loading the plugin onto my mixer, the plugin crashed/froze FL. 
I tried a fresh installation of the plugin, no dice.  
I tried with both audio unit and vst, the AU version doesn't show up.
Is this an issue on my end and Is there a fix for this?

**Comment by mourednik** [comment]
I would expect this plugin to be unusable on the latest MacOS.

This plugin was compiled 8 years ago. By Apple standards, that's like 8,000 years ago. They move fast and break backwards compatibility with every new release.

I started working on a new version but it will take a while. I have to redesign and rewrite all the UI code to work with the latest JUCE framework.
