### ISSUE TITLE
MacOS compatibility - Can I help?

### ISSUE THREAD

**Issue by Tinusw** [mourednik/argotlunar#3]
`
I've received reports that it doesn't work in MacOS 10.11 and 10.12. Apple broke backwards compatibility. I need to update the code but presently don't have a Mac to develop with.
`

Just curious if you will be addressing this or if there's anyway I can help out?

I love your VST and find myself missing it quite a lot :)

**Comment by mourednik** [comment]
I'm going to update the project to use the latest version of Juce. Then I will get someone to compile new Mac OS versions.

**Comment by Tinusw** [comment]
Awesome! I've got a mac so yell out if I can help!

**Comment by blueben** [comment]
Also interested in seeing an update for MacOS.

**Comment by mourednik** [comment]
Sorry, it took a while for me to get started on this. I have begun the process of updating it. I'm also going to make some improvements to the GUI and audio processor.

**Comment by ClaudeNabrun** [comment]
Hi all. 

Very nice to read Argotlunar will get updated for OS X. It is a very powerful granular tool that I also love to use, really missing it since a few OS X version. 

Very nice to see it will also get a little face lift while there. Thank you mourednik ! Any approx.. date when the update could be available ?

**Comment by ClaudeNabrun** [comment]
Hello all

Any news or update on Argotlunar? Seems like the dev -mourednik- started months ago working on it. Hope it goes well and we'll see a new version soon. 

@mourednik: any way we can help to test or try?

**Comment by bbbmusic** [comment]
I tested Argotlunar on MacOs 10.13.6 (High Sierra). 
It works fine in Max 8.0.5 and Logic Pro X 10.4.4 
but does not appear in Ableton Live 10.0.6 (neither AU nor VST version).

**Comment by hexdump0815** [comment]
for me the vst version appears and works in ableton live lite 10.0.6 running on 10.12.6 sierra - the au version does not appear for me neither ...

**Comment by bbbmusic** [comment]
Good news, just tested again:
argotlunar 2.0.6 (vst only) works with Ableton 10.1.2, MacOS 10.14.6

**Comment by mourednik** [comment]
Sorry I got diverted from this project after I saw how much work is involved to rewrite it for a newer JUCE version. Closing this issue now and will see if I have time this Christmas break.
