### ISSUE TITLE
loading of xml banks does not work on linux

### ISSUE THREAD

**Issue by hexdump0815** [mourednik/argotlunar#4]
hello,

first a bit thinks for this really nice plugin. now to the bug report :) - when i try to load the banks preset file provided by clicking on options and the load banks xml file i see the following behaviour:
* linux 64bit - ardour 5.12 - ubuntu 18.04 - your provided plugin: nothing happens when i click on options, so i have no chance to get to the load banks from xml option
* linux 64bit - ardour 5.12 - ubuntu 18.04 - plugin compile by myself: i get the menu and can load the banks preset file, but it does not really get loaded - same for saving banks or a program: i get the file dialog to save and everything looks like its working, but the file does not exist afterwards - looks a bit like the file operations are somehow disabled internally somewhere
* macos sierra - logic pro 9 - plugin provided by you: everything works as expected

do you or someone else has any idea why it is not working in the linux case?

a lot of thanks in advance and best wishes - hexdump

**Comment by hexdump0815** [comment]
i just verified, that the exact same problems happen when using the plugin in qtractor too - so it has nothing to do with running in ardour. i also verified it to be the same on armhf (arm 32bit) and aarch64 (arm 64bit) builds.

**Comment by hexdump0815** [comment]
just in case someone else runs into the same problem - i found some kind of solution: first i realized, that both qtractor and ardour offer a way to save presets for plugins as part of their plugin host functionality - in qtractor you can save a preset directly into a file and in ardour presets are saved in a special format to ~/.config/ardour/presets ... by creating such an ardour preset, converting to to fxp with https://github.com/SpotlightKid/ardour2fxp and replacing the content with the one from the argotlunar presets, padding the filesize properly and converting it back i was able to create an aroud preset file containing the default argotlunar presets. this is the resulting ardour preset file:
`$ cat .config/ardour5/presets/vst-1095911217 
<?xml version='1.0' encoding='UTF-8'?>
<VSTPresets>
<ChunkPreset label="ambience" numParams="233" uri="VST:1095911217:xc3469ca11c7698fd34d6b66570e2178aa3800ab4" version="1">VkMyIZ0DAAA8QVJHT1RMVU5BUjJfUFJPR1JBTSBwcm9ncmFtX25hbWU9ImFtYmllbmNlIiBncmFpbnM9IjEiIG1peD0iMSIgaW5wdXRfZ2Fpbj0iMSIgZmVlZGJhY2s9IjAuNzIxMDAwMDE2IiBhbXA9IjAuNSIgYW1wdj0iMC41IiBwYW49IjAuNSIgcGFudj0iMSIgZGVsYXk9IjAuMjg3OTk5OTg4IiBkZWxheXY9IjAuMDgyMDAwMDAyMyIgaW90PSIwIiBpb3R2PSIwLjE1MTk5OTk5NSIgZHVyPSIwLjYwNzk5OTk4IiBkdXJ2PSIwLjIzMTk5OTk5MyIgdHJhbnM9IjAuNSIgdHJhbnN2PSIwIiBnbGlzcz0iMC41IiBnbGlzc3Y9IjAuMDE2MDAwMDAwOCIgZmlsdGVyX3R5cGU9IjAuMTY2NjY2NjcyIiBmZnJlcT0iMC40ODM5OTk5OTciIGZmcmVxdj0iMC4yNzIwMDAwMTUiIGZxPSIwIiBmcXY9IjAuNSIgZW52X3R5cGU9IjAiIGVudl9zaGFwZT0iMC4wNTAwMDAwMDA3IiBlbnZfc2tldz0iMC41IiBkZWxheV9xdWFudD0iMC4wNzY5MjMwNzk4IiBkdXJfcXVhbnQ9IjAuMDcxNDI4NTc0NiIgaW90X3F1YW50PSIwLjA3NjkyMzA3OTgiIHRyYW5zX3RvZ2dsZT0iMCIgZ2xpc3NfdG9nZ2xlPSIxIiBmcmVlemVfdG9nZ2xlPSIwIiBzY2FsZV9rZXk9IjAiIG1hdHJpeF9tb2RfMT0iMC41IiBtYXRyaXhfbW9kXzI9IjAuNSIgbWF0cml4X21vZF8zPSIwLjUiIHNjYWxlPSIxIiBtYXRyaXhfc3JjXzE9IjAiIG1hdHJpeF9zcmNfMj0iMCIgbWF0cml4X3NyY18zPSIwIiBtYXRyaXhfZGVzdF8xPSIwIiBtYXRyaXhfZGVzdF8yPSIwIiBtYXRyaXhfZGVzdF8zPSIwIiBtYXRyaXhfbW9kZV8xPSIwIiBtYXRyaXhfbW9kZV8yPSIwIiBtYXRyaXhfbW9kZV8zPSIwIiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIA==</ChunkPreset>
<ChunkPreset label="cloud 7" numParams="233" uri="VST:1095911217:x86c03483c597cc4123779de29735eb7d28578aef" version="1">VkMyIZ0DAAA8QVJHT1RMVU5BUjJfUFJPR1JBTSBwcm9ncmFtX25hbWU9ImNsb3VkIDciIGdyYWlucz0iMSIgbWl4PSIxIiBpbnB1dF9nYWluPSIxIiBmZWVkYmFjaz0iMC4zNTI5OTk5ODUiIGFtcD0iMC41MTk5OTk5ODEiIGFtcHY9IjAuNSIgcGFuPSIwLjUiIHBhbnY9IjEiIGRlbGF5PSIwLjE3NTk5OTk5OSIgZGVsYXl2PSIwLjY2Mzk5OTk3NSIgaW90PSIwIiBpb3R2PSIwLjg4ODAwMDAxMSIgZHVyPSIxIiBkdXJ2PSIwLjI4MDAwMDAwMSIgdHJhbnM9IjAuNjQzOTk5OTk0IiB0cmFuc3Y9IjAiIGdsaXNzPSIwLjUiIGdsaXNzdj0iMC4wMTIwMDAwMDAxIiBmaWx0ZXJfdHlwZT0iMC4zMzMzMzMzNDMiIGZmcmVxPSIwLjM0Nzk5OTk5IiBmZnJlcXY9IjAuMzAwMDAwMDEyIiBmcT0iMCIgZnF2PSIwIiBlbnZfdHlwZT0iMCIgZW52X3NoYXBlPSIwLjk0OTk5OTk4OCIgZW52X3NrZXc9IjAuNTI0OTk5OTc2IiBkZWxheV9xdWFudD0iMC4wNzE0Mjg1NzQ2IiBkdXJfcXVhbnQ9IjAuMDcxNDI4NTc0NiIgaW90X3F1YW50PSIwLjA3NjkyMzA3OTgiIHRyYW5zX3RvZ2dsZT0iMSIgZ2xpc3NfdG9nZ2xlPSIwIiBmcmVlemVfdG9nZ2xlPSIwIiBzY2FsZV9rZXk9IjAiIG1hdHJpeF9tb2RfMT0iMC41IiBtYXRyaXhfbW9kXzI9IjAuNSIgbWF0cml4X21vZF8zPSIwLjUiIHNjYWxlPSIxIiBtYXRyaXhfc3JjXzE9IjAiIG1hdHJpeF9zcmNfMj0iMCIgbWF0cml4X3NyY18zPSIwIiBtYXRyaXhfZGVzdF8xPSIwIiBtYXRyaXhfZGVzdF8yPSIwIiBtYXRyaXhfZGVzdF8zPSIwIiBtYXRyaXhfbW9kZV8xPSIwIiBtYXRyaXhfbW9kZV8yPSIwIiBtYXRyaXhfbW9kZV8zPSIwIiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgLz4ACg==</ChunkPreset>
<ChunkPreset label="echoes" numParams="233" uri="VST:1095911217:x80adb9a680f469e4cb63f40ae855a20d29c6617a" version="1">VkMyIZ0DAAA8QVJHT1RMVU5BUjJfUFJPR1JBTSBwcm9ncmFtX25hbWU9ImVjaG9lcyIgZ3JhaW5zPSIxIiBtaXg9IjEiIGlucHV0X2dhaW49IjEiIGZlZWRiYWNrPSIwLjUiIGFtcD0iMC41IiBhbXB2PSIwLjIxMTk5OTk5NyIgcGFuPSIwLjUiIHBhbnY9IjAuNDA0MDAwMDE0IiBkZWxheT0iMCIgZGVsYXl2PSIwLjE5NTk5OTk5NSIgaW90PSIwIiBpb3R2PSIwLjQ3NjAwMDAxMSIgZHVyPSIwLjI4NDAwMDAwOSIgZHVydj0iMC4zOTU5OTk5OTgiIHRyYW5zPSIwLjUiIHRyYW5zdj0iMCIgZ2xpc3M9IjAuNSIgZ2xpc3N2PSIwLjAyNDAwMDAwMDIiIGZpbHRlcl90eXBlPSIwLjE2NjY2NjY3MiIgZmZyZXE9IjAuMzYzOTk5OTkzIiBmZnJlcXY9IjAuMzk1OTk5OTk4IiBmcT0iMCIgZnF2PSIxIiBlbnZfdHlwZT0iMCIgZW52X3NoYXBlPSIxIiBlbnZfc2tldz0iMC41IiBkZWxheV9xdWFudD0iMC42MTUzODQ2MzgiIGR1cl9xdWFudD0iMC44NTcxNDI5MjUiIGlvdF9xdWFudD0iMC4wNzY5MjMwNzk4IiB0cmFuc190b2dnbGU9IjAiIGdsaXNzX3RvZ2dsZT0iMSIgZnJlZXplX3RvZ2dsZT0iMCIgc2NhbGVfa2V5PSIwIiBtYXRyaXhfbW9kXzE9IjAuMjcwMDAwMDExIiBtYXRyaXhfbW9kXzI9IjAuMjcwMDAwMDExIiBtYXRyaXhfbW9kXzM9IjAuNSIgc2NhbGU9IjEiIG1hdHJpeF9zcmNfMT0iNCIgbWF0cml4X3NyY18yPSIwIiBtYXRyaXhfc3JjXzM9IjAiIG1hdHJpeF9kZXN0XzE9IjgiIG1hdHJpeF9kZXN0XzI9IjAiIG1hdHJpeF9kZXN0XzM9IjAiIG1hdHJpeF9tb2RlXzE9IjAiIG1hdHJpeF9tb2RlXzI9IjAiIG1hdHJpeF9tb2RlXzM9IjAiICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgLz4ACg==</ChunkPreset>
<ChunkPreset label="grainforest" numParams="233" uri="VST:1095911217:xf779c3a1ef9afe3184e15d457fa20022a52adc5b" version="1">VkMyIZ0DAAA8QVJHT1RMVU5BUjJfUFJPR1JBTSBwcm9ncmFtX25hbWU9ImdyYWluZm9yZXN0IiBncmFpbnM9IjEiIG1peD0iMSIgaW5wdXRfZ2Fpbj0iMSIgZmVlZGJhY2s9IjEiIGFtcD0iMC42OTU5OTk5OCIgYW1wdj0iMC41IiBwYW49IjAuNSIgcGFudj0iMSIgZGVsYXk9IjAuMTc1OTk5OTk5IiBkZWxheXY9IjAuODA4MDAwMDI4IiBpb3Q9IjAiIGlvdHY9IjAuNzk2MDAwMDA0IiBkdXI9IjEiIGR1cnY9IjAuMjgwMDAwMDAxIiB0cmFucz0iMC4zNjAwMDAwMTQiIHRyYW5zdj0iMCIgZ2xpc3M9IjAuNSIgZ2xpc3N2PSIwLjAxMjAwMDAwMDEiIGZpbHRlcl90eXBlPSIwLjUiIGZmcmVxPSIwLjQ3OTk5OTk4OSIgZmZyZXF2PSIwLjI4MDAwMDAwMSIgZnE9IjAiIGZxdj0iMC45NTIwMDAwMjIiIGVudl90eXBlPSIwIiBlbnZfc2hhcGU9IjAuOTQ5OTk5OTg4IiBlbnZfc2tldz0iMC41MjQ5OTk5NzYiIGRlbGF5X3F1YW50PSIwLjA3MTQyODU3NDYiIGR1cl9xdWFudD0iMC4wNzE0Mjg1NzQ2IiBpb3RfcXVhbnQ9IjAuMDc2OTIzMDc5OCIgdHJhbnNfdG9nZ2xlPSIxIiBnbGlzc190b2dnbGU9IjAiIGZyZWV6ZV90b2dnbGU9IjAiIHNjYWxlX2tleT0iMCIgbWF0cml4X21vZF8xPSIwLjUiIG1hdHJpeF9tb2RfMj0iMC41IiBtYXRyaXhfbW9kXzM9IjAuNSIgc2NhbGU9IjEiIG1hdHJpeF9zcmNfMT0iMCIgbWF0cml4X3NyY18yPSIwIiBtYXRyaXhfc3JjXzM9IjAiIG1hdHJpeF9kZXN0XzE9IjAiIG1hdHJpeF9kZXN0XzI9IjAiIG1hdHJpeF9kZXN0XzM9IjAiIG1hdHJpeF9tb2RlXzE9IjAiIG1hdHJpeF9tb2RlXzI9IjAiIG1hdHJpeF9tb2RlXzM9IjAiICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIA==</ChunkPreset>
<ChunkPreset label="grainverb" numParams="233" uri="VST:1095911217:xf26bd765b0c37ca27f0e81489442a11631972655" version="1">VkMyIZ0DAAA8QVJHT1RMVU5BUjJfUFJPR1JBTSBwcm9ncmFtX25hbWU9ImdyYWludmVyYiIgZ3JhaW5zPSIxIiBtaXg9IjAuNDA0MDAwMDE0IiBpbnB1dF9nYWluPSIxIiBmZWVkYmFjaz0iMC41MzUwMDAwMjYiIGFtcD0iMC41IiBhbXB2PSIwLjUiIHBhbj0iMC41IiBwYW52PSIxIiBkZWxheT0iMC4yNTIwMDAwMDQiIGRlbGF5dj0iMC4yMTc5OTk5OTUiIGlvdD0iMCIgaW90dj0iMCIgZHVyPSIwLjUwNDAwMDAwOCIgZHVydj0iMC4wMjgwMDAwMDA5IiB0cmFucz0iMC41IiB0cmFuc3Y9IjAiIGdsaXNzPSIwLjUiIGdsaXNzdj0iMCIgZmlsdGVyX3R5cGU9IjAuNSIgZmZyZXE9IjAuMzAwMDAwMDEyIiBmZnJlcXY9IjAuMTMxOTk5OTk5IiBmcT0iMCIgZnF2PSIwIiBlbnZfdHlwZT0iMSIgZW52X3NoYXBlPSIwLjA1MDAwMDAwMDciIGVudl9za2V3PSIwLjY5ODAwMDAxNCIgZGVsYXlfcXVhbnQ9IjAuMDc2OTIzMDc5OCIgZHVyX3F1YW50PSIwLjA3MTQyODU3NDYiIGlvdF9xdWFudD0iMC4wNzY5MjMwNzk4IiB0cmFuc190b2dnbGU9IjAiIGdsaXNzX3RvZ2dsZT0iMCIgZnJlZXplX3RvZ2dsZT0iMCIgc2NhbGVfa2V5PSIwIiBtYXRyaXhfbW9kXzE9IjAuNSIgbWF0cml4X21vZF8yPSIwLjUiIG1hdHJpeF9tb2RfMz0iMC41IiBzY2FsZT0iMSIgbWF0cml4X3NyY18xPSIwIiBtYXRyaXhfc3JjXzI9IjAiIG1hdHJpeF9zcmNfMz0iMCIgbWF0cml4X2Rlc3RfMT0iMCIgbWF0cml4X2Rlc3RfMj0iMCIgbWF0cml4X2Rlc3RfMz0iMCIgbWF0cml4X21vZGVfMT0iMCIgbWF0cml4X21vZGVfMj0iMCIgbWF0cml4X21vZGVfMz0iMCIgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgLz4ACg==</ChunkPreset>
<ChunkPreset label="mescalin delay" numParams="233" uri="VST:1095911217:x6806eedc97aa888973ff7b602fa22c0850123229" version="1">VkMyIZ0DAAA8QVJHT1RMVU5BUjJfUFJPR1JBTSBwcm9ncmFtX25hbWU9Im1lc2NhbGluIGRlbGF5IiBncmFpbnM9IjAuNSIgbWl4PSIwLjYwMDAwMDAyNCIgaW5wdXRfZ2Fpbj0iMSIgZmVlZGJhY2s9IjAuNSIgYW1wPSIwLjcwMzk5OTk5NiIgYW1wdj0iMC40OTIwMDAwMTQiIHBhbj0iMC41IiBwYW52PSIwLjU5NjAwMDAxNiIgZGVsYXk9IjAuNDk1OTk5OTkyIiBkZWxheXY9IjAuMDY0MDAwMDAzIiBpb3Q9IjAiIGlvdHY9IjAuNDcyMDAwMDAzIiBkdXI9IjAuNTk2MDAwMDE2IiBkdXJ2PSIwLjMyODAwMDAwOSIgdHJhbnM9IjAuNSIgdHJhbnN2PSIwIiBnbGlzcz0iMC41IiBnbGlzc3Y9IjAuMDE2MDAwMDAwOCIgZmlsdGVyX3R5cGU9IjAuMTY2NjY2NjcyIiBmZnJlcT0iMC4yOTE5OTk5OTYiIGZmcmVxdj0iMC4zNjAwMDAwMTQiIGZxPSIwIiBmcXY9IjAuNSIgZW52X3R5cGU9IjAiIGVudl9zaGFwZT0iMC4wNTAwMDAwMDA3IiBlbnZfc2tldz0iMC41IiBkZWxheV9xdWFudD0iMC4xNTM4NDYxNiIgZHVyX3F1YW50PSIwLjA3MTQyODU3NDYiIGlvdF9xdWFudD0iMC4wNzY5MjMwNzk4IiB0cmFuc190b2dnbGU9IjAiIGdsaXNzX3RvZ2dsZT0iMSIgZnJlZXplX3RvZ2dsZT0iMCIgc2NhbGVfa2V5PSIwIiBtYXRyaXhfbW9kXzE9IjAuNSIgbWF0cml4X21vZF8yPSIwLjUiIG1hdHJpeF9tb2RfMz0iMC41IiBzY2FsZT0iMSIgbWF0cml4X3NyY18xPSIwIiBtYXRyaXhfc3JjXzI9IjAiIG1hdHJpeF9zcmNfMz0iMCIgbWF0cml4X2Rlc3RfMT0iMCIgbWF0cml4X2Rlc3RfMj0iMCIgbWF0cml4X2Rlc3RfMz0iMCIgbWF0cml4X21vZGVfMT0iMCIgbWF0cml4X21vZGVfMj0iMCIgbWF0cml4X21vZGVfMz0iMCIgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgLz4ACg==</ChunkPreset>
<ChunkPreset label="middle A" numParams="233" uri="VST:1095911217:x4993930a392600991f3153ed1b6810d3839e047c" version="1">VkMyIZ0DAAA8QVJHT1RMVU5BUjJfUFJPR1JBTSBwcm9ncmFtX25hbWU9Im1pZGRsZSBBIiBncmFpbnM9IjEiIG1peD0iMSIgaW5wdXRfZ2Fpbj0iMC41MDQwMDAwMDgiIGZlZWRiYWNrPSIwLjUiIGFtcD0iMC41IiBhbXB2PSIwLjUiIHBhbj0iMC41IiBwYW52PSIxIiBkZWxheT0iMC4yNTk5OTk5OSIgZGVsYXl2PSIwLjIwODAwMDAwNCIgaW90PSIwIiBpb3R2PSIwLjgyNDAwMDAwMSIgZHVyPSIxIiBkdXJ2PSIwLjgzNjAwMDAyNSIgdHJhbnM9IjAuMzYzOTk5OTkzIiB0cmFuc3Y9IjAiIGdsaXNzPSIwLjUiIGdsaXNzdj0iMC4wNjQwMDAwMDMiIGZpbHRlcl90eXBlPSIwLjgzMzMzMzMxMyIgZmZyZXE9IjAuMzMzMDAwMDA0IiBmZnJlcXY9IjAiIGZxPSIwIiBmcXY9IjAiIGVudl90eXBlPSIwIiBlbnZfc2hhcGU9IjAuNDY1OTk5OTkxIiBlbnZfc2tldz0iMC40ODg5OTk5OTMiIGRlbGF5X3F1YW50PSIwLjA3NjkyMzA3OTgiIGR1cl9xdWFudD0iMC4wNzE0Mjg1NzQ2IiBpb3RfcXVhbnQ9IjAuMDc2OTIzMDc5OCIgdHJhbnNfdG9nZ2xlPSIxIiBnbGlzc190b2dnbGU9IjAiIGZyZWV6ZV90b2dnbGU9IjAiIHNjYWxlX2tleT0iMCIgbWF0cml4X21vZF8xPSIwLjk0OTk5OTk4OCIgbWF0cml4X21vZF8yPSIwLjk0OTk5OTk4OCIgbWF0cml4X21vZF8zPSIwLjUiIHNjYWxlPSIxIiBtYXRyaXhfc3JjXzE9IjYiIG1hdHJpeF9zcmNfMj0iMCIgbWF0cml4X3NyY18zPSIwIiBtYXRyaXhfZGVzdF8xPSI5IiBtYXRyaXhfZGVzdF8yPSIwIiBtYXRyaXhfZGVzdF8zPSIwIiBtYXRyaXhfbW9kZV8xPSIxIiBtYXRyaXhfbW9kZV8yPSIwIiBtYXRyaXhfbW9kZV8zPSIwIiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgLz4ACg==</ChunkPreset>
<ChunkPreset label="slowed" numParams="233" uri="VST:1095911217:x7915349d0ab3b20f61ff9e3dab13f62d1ef1cdb3" version="1">VkMyIZ0DAAA8QVJHT1RMVU5BUjJfUFJPR1JBTSBwcm9ncmFtX25hbWU9InNsb3dlZCIgZ3JhaW5zPSIxIiBtaXg9IjEiIGlucHV0X2dhaW49IjEiIGZlZWRiYWNrPSIwIiBhbXA9IjAuNSIgYW1wdj0iMC41IiBwYW49IjAuNSIgcGFudj0iMSIgZGVsYXk9IjAiIGRlbGF5dj0iMCIgaW90PSIwIiBpb3R2PSIxIiBkdXI9IjAuODUxOTk5OTk4IiBkdXJ2PSIxIiB0cmFucz0iMC4yNTYwMDAwMTIiIHRyYW5zdj0iMCIgZ2xpc3M9IjAuNSIgZ2xpc3N2PSIwLjAxMzAwMDAwMDMiIGZpbHRlcl90eXBlPSIwLjUiIGZmcmVxPSIwLjIxOTk5OTk5OSIgZmZyZXF2PSIwLjM1MTk5OTk5OCIgZnE9IjAiIGZxdj0iMC43OTYwMDAwMDQiIGVudl90eXBlPSIwLjUiIGVudl9zaGFwZT0iMC41MDQwMDAwMDgiIGVudl9za2V3PSIwLjUiIGRlbGF5X3F1YW50PSIwLjA3NjkyMzA3OTgiIGR1cl9xdWFudD0iMSIgaW90X3F1YW50PSIwLjA3NjkyMzA3OTgiIHRyYW5zX3RvZ2dsZT0iMSIgZ2xpc3NfdG9nZ2xlPSIxIiBmcmVlemVfdG9nZ2xlPSIwIiBzY2FsZV9rZXk9IjAiIG1hdHJpeF9tb2RfMT0iMC41IiBtYXRyaXhfbW9kXzI9IjAuNSIgbWF0cml4X21vZF8zPSIwLjUiIHNjYWxlPSIxIiBtYXRyaXhfc3JjXzE9IjAiIG1hdHJpeF9zcmNfMj0iMCIgbWF0cml4X3NyY18zPSIwIiBtYXRyaXhfZGVzdF8xPSIwIiBtYXRyaXhfZGVzdF8yPSIwIiBtYXRyaXhfZGVzdF8zPSIwIiBtYXRyaXhfbW9kZV8xPSIwIiBtYXRyaXhfbW9kZV8yPSIwIiBtYXRyaXhfbW9kZV8zPSIwIiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgLz4ACg==</ChunkPreset>
</VSTPresets>`

**Comment by hoemon** [comment]
For me the plugin does not even load in any host app in linux

**Comment by trebmuh** [comment]
@hoemon just to mention that there is a port of argolunar here: https://github.com/DISTRHO/DISTRHO-Ports-Extra

**Comment by hexdump0815** [comment]
cool - good to know - thanks for the info
