### ISSUE TITLE
Error when running on Ardour: "[ERROR]: LADSPA: module "/usr/lib/ladspa/argotlunar.so" has no descriptor function."

### ISSUE THREAD

**Issue by alemangui** [mourednik/argotlunar#6]
Hello,

I have been trying to install Argotlunar as an Ardour plugin without success. I keep getting there errors:

```
[ERROR]: LADSPA: module "/usr/lib/ladspa/argotlunar.so" has no descriptor function.
[ERROR]: 'ladspa_descriptor': /usr/lib/ladspa/argotlunar.so: undefined symbol: ladspa_descriptor
```

I downloaded the files and placed the .so files under /usr/lib/ladspa along with the other ones (I am on Ubuntu 18,04) but every time I make Ardour scan for plugins I get the error above.

Any help is greatly appreciated

**Comment by trebmuh** [comment]
How did you install ArgotLunar? From a package or from a compilation?

**Comment by mourednik** [comment]
ArgotLunar is a VST plugin. It will not work if you try to install it as a LADSPA plugin. You need to follow the instructions for installing VST plugins in Ardour, or try the LV2 version as suggested above.
