### ISSUE TITLE
Build Error - ‘empty’ is not a member of ‘juce::String’

### ISSUE THREAD

**Issue by tank-trax** [mourednik/argotlunar#7]
Debian Buster 10.6
trying to build VST3 using JUCE 6.04

```
Compiling Parameters.cpp
../../Source/Parameters.cpp: In member function ‘const juce::String Parameters::getParameterName(int)’:
../../Source/Parameters.cpp:243:20: error: ‘empty’ is not a member of ‘juce::String’
     return String::empty;
```

**Comment by mourednik** [comment]
Hello. It is a major piece of work to upgrade to a newer JUCE version. I'm closing this issue and will see how much work is involved to upgrade. Thanks.

**Comment by tank-trax** [comment]
thanks for the reply, I thought I'd give it a try :-)

**Comment by tank-trax** [comment]
this happens with the VST2 as well
